<a href="https://colab.research.google.com/github/Thalapathi26/AI_ML/blob/main/nlp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords #remove and,or,is
from nltk.stem import WordNetLemmatizer #change root form
from sklearn.feature_extraction.text import TfidfVectorizer # change numerical method
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
df=pd.read_csv('/content/Restaurant_Reviews.tsv', delimiter='\t')

In [ ]:
df

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [ ]:
stopwords=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
def preprocess(text):
  text=re.sub('[^a-zA-Z]',' ',text)
  text=text.lower()
  words=text.split()
  words=[lemmatizer.lemmatize(word) for word in words if word not in stopwords]
  return" ".join(words)

df['Review']=df['Review'].apply(preprocess)
df

                                                Review  Liked
0                                      wow loved place      1
1                                           crust good      0
2                                  tasty texture nasty      0
3    stopped late may bank holiday rick steve recom...      1
4                           selection menu great price      1
..                                                 ...    ...
995                  think food flavor texture lacking      0
996                            appetite instantly gone      0
997                    overall impressed would go back      0
998  whole experience underwhelming think go ninja ...      0
999  wasted enough life poured salt wound drawing t...      0

[1000 rows x 2 columns]

In [ ]:
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(df['Review'])
y=df['Liked']

In [ ]:
df['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [ ]:
x=(df['Review'])
y=(df['Liked'])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SimpleRNN

In [ ]:
print(x_train)

29                                  worst salmon sashimi
535       excellent new restaurant experienced frenchman
695                              went lunch service slow
557          think restaurant suffers trying hard enough
836                               lunch great experience
                             ...
106    food delicious bartender attentive personable ...
270                            veggitarian platter world
860        place pretty good nice little vibe restaurant
435             huge awkward lb piece cow th gristle fat
102                   best buffet town price cannot beat
Name: Review, Length: 800, dtype: object

In [ ]:
#x_train = x_train.toarray()
#x_test = x_test.toarray()

AttributeError: 'Series' object has no attribute 'toarray'

In [ ]:
model=Sequential()
model.add(Embedding(input_dim=10000,output_dim=32))
model.add(SimpleRNN(512,activation='tanh'))

model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.utils import validation
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
lstm=model.fit(x_train, y_train, epochs=15, batch_size=32, validation_data=(x_test, y_test))

ValueError: Invalid dtype: object

In [ ]:
prediction=model.predict(x_test)
prediction

7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 471ms/step

array([[0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545],
       [0.49431545]], dtype=float32)

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1])

In [ ]:
accuracy_score(y_test,y_pred)

0.77

In [ ]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred_1=rfc.predict(x_test)
y_pred_1

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1])

In [ ]:
accuracy_score(y_test,y_pred_1)

0.705

In [1]:
   sample=['nice movie']
sample_clean=[preprocess(s)for s in sample]
sample_vector=vectorizer.transform(sample_clean)
if model.predict(sample_vector)==1:
  print('positive')
else:
  print('negative')

NameError: name 'preprocess' is not defined